// filters.js — 100 filter presets.
// Every filter is a set of overrides merged onto DEFAULT_PARAMS.
// Numeric params roughly follow the original spec table, scaled to 0–1 shader units.

const DEFAULT_PARAMS = {
  exp: 0, contrast: 0, sat: 0, temp: 0, tint: 0,
  highlights: 0, shadows: 0, fade: 0, grain: 0, vignette: 0, clarity: 0,
  splitShadow: [0.5, 0.5, 0.5], splitHighlight: [0.5, 0.5, 0.5], splitAmount: 0,
  channelSat: [0, 0, 0],
  posterize: 0, edge: 0, rgbShift: 0, glitch: 0, dust: 0, glow: 0, vhs: 0,
};

function mk(en, cn, overrides, prompt) {
  return { en, cn, prompt, params: Object.assign({}, DEFAULT_PARAMS, overrides) };
}

const TEAL = [0.40, 0.50, 0.58];
const ORANGE = [0.62, 0.52, 0.40];
const ROSE_HI = [0.58, 0.42, 0.55];
const PURPLE_HI = [0.56, 0.38, 0.62];
const BLUE_SHADOW = [0.42, 0.42, 0.62];

const FILTERS = [
  mk("Pure", "纯净原色", { exp: .03, contrast: .03, sat: .02 }, "natural realistic colors, subtle enhancement"),
  mk("Clean", "干净通透", { exp: .06, contrast: .04, sat: .03 }, "clean modern photography, clear natural colors"),
  mk("Fresh", "明亮清新", { exp: .08, temp: -.05, sat: .05 }, "fresh bright photography, slightly cool tones"),
  mk("Clear", "通透层次", { contrast: .08, highlights: -.08, shadows: .08 }, "crystal clear details, balanced dynamic range"),
  mk("Bright", "整体明亮", { exp: .12, shadows: .10 }, "bright airy photography, lifted shadows"),
  mk("Soft", "柔和低对比", { contrast: -.08, highlights: -.05, fade: .05 }, "soft photography, gentle contrast, smooth tones"),
  mk("Airy", "高亮轻盈", { exp: .15, contrast: -.08, sat: -.02 }, "airy high-key photography, soft whites"),
  mk("Pure Skin", "自然肤色", { exp: .05, sat: -.02, channelSat: [-.08, 0, 0] }, "natural skin tones, clean portrait photography"),
  mk("Crystal", "清晰锐利", { contrast: .10, clarity: .12, sat: .03 }, "crisp detailed photography, sharp textures"),
  mk("True Color", "真实还原", { contrast: .02, sat: -.02 }, "accurate true-to-life colors"),
  mk("Warm", "温暖色调", { temp: .12, sat: .03 }, "warm natural photography, cozy tones"),
  mk("Golden", "金黄阳光", { temp: .22, highlights: .05 }, "golden sunlight, warm highlights"),
  mk("Honey", "蜂蜜柔暖", { temp: .28, sat: .05, fade: .03 }, "honey golden tones, warm soft photography"),
  mk("Peach", "桃粉色调", { temp: .15, tint: .08 }, "peach tones, soft warm portrait"),
  mk("Cream", "奶油色调", { temp: .18, contrast: -.08, fade: .08 }, "creamy warm tones, soft highlights"),
  mk("Latte", "咖啡奶油", { temp: .25, sat: -.08, fade: .10 }, "latte beige tones, muted warm colors"),
  mk("Sunset", "日落橙红", { temp: .30, channelSat: [.15, .07, 0] }, "dramatic sunset orange tones"),
  mk("Amber", "深琥珀色", { temp: .25, contrast: .08 }, "rich amber color grading"),
  mk("Apricot", "杏桃橙粉", { temp: .20, tint: .12 }, "soft apricot and peach tones"),
  mk("Summer Glow", "夏日阳光", { exp: .08, temp: .18, sat: .08 }, "bright summer sunlight, warm glow"),
  mk("Cool", "轻微冷色", { temp: -.15 }, "cool clean color grading"),
  mk("Ice", "冰蓝色调", { temp: -.30, sat: -.05 }, "icy blue tones, cold atmosphere"),
  mk("Arctic", "冷白蓝灰", { temp: -.35, contrast: .05 }, "arctic cold tones, blue-gray palette"),
  mk("Ocean", "海洋蓝调", { temp: -.20, channelSat: [0, 0, .15] }, "deep ocean blue tones"),
  mk("Blue Hour", "蓝调黄昏", { temp: -.30, exp: -.05, channelSat: [0, 0, .12] }, "blue hour photography, cool twilight"),
  mk("Frost", "冰霜质感", { temp: -.35, sat: -.10 }, "frosty muted blue atmosphere"),
  mk("Cyan", "青蓝色调", { temp: -.20, tint: -.08 }, "cyan color grading, cool tones"),
  mk("Deep Blue", "深蓝电影感", { temp: -.25, contrast: .15 }, "deep cinematic blue tones"),
  mk("Rain", "阴雨天气感", { exp: -.08, sat: -.12, temp: -.18 }, "rainy day photography, muted cool tones"),
  mk("Winter", "冬季冷调", { temp: -.25, highlights: -.08 }, "winter photography, cool clean highlights"),
  mk("35mm", "经典胶片", { contrast: -.05, fade: .08, grain: .18 }, "authentic 35mm analog film, subtle grain"),
  mk("Portra", "柔和肤色胶片", { sat: -.08, contrast: -.05, grain: .12 }, "portrait film, natural skin tones, soft grain"),
  mk("Kodak", "暖黄经典胶片", { temp: .10, sat: .05, grain: .15 }, "Kodak-inspired warm 35mm film aesthetic"),
  mk("Fuji", "清新偏绿胶片", { temp: -.03, channelSat: [0, .08, 0], grain: .12 }, "Fuji-inspired film, subtle green tones"),
  mk("Classic Film", "传统胶片", { sat: -.08, fade: .12, grain: .20 }, "classic analog film, faded colors, grain"),
  mk("Soft Film", "柔和胶片", { contrast: -.12, fade: .12, grain: .15 }, "soft film photography, gentle contrast"),
  mk("Negative", "负片质感", { sat: -.10, contrast: -.08, grain: .22 }, "negative film aesthetic, analog texture"),
  mk("Disposable", "一次性胶片相机", { contrast: .05, grain: .30, vignette: .12 }, "disposable camera aesthetic, flash, grain"),
  mk("Analog", "模拟相机感", { fade: .10, grain: .25, sat: -.05 }, "authentic analog camera photography"),
  mk("Film Dust", "胶片灰尘纹理", { grain: .25, fade: .15, dust: .5 }, "vintage film with dust and scratches"),
  mk("Vintage", "泛黄褪色", { temp: .18, fade: .20 }, "nostalgic vintage photography, faded colors"),
  mk("Retro", "复古年代感", { sat: -.05, temp: .12, grain: .20 }, "retro analog photography, nostalgic colors"),
  mk("Sepia", "棕褐老照片", { sat: -.45, temp: .35 }, "classic sepia photograph"),
  mk("Old Camera", "老相机质感", { contrast: -.05, grain: .30, fade: .20 }, "old camera photography, faded grain"),
  mk("90s", "90年代胶片", { sat: .03, grain: .25, fade: .10 }, "authentic 1990s film photography"),
  mk("80s", "80年代暖色", { temp: .20, sat: .08, grain: .25 }, "1980s vintage photography, warm colors"),
  mk("70s", "70年代黄褐", { temp: .30, sat: -.05, fade: .20 }, "1970s film photography, warm faded tones"),
  mk("Nostalgia", "怀旧柔和", { contrast: -.10, fade: .18, grain: .15 }, "nostalgic dreamy analog photography"),
  mk("Faded", "明显褪色", { contrast: -.15, fade: .30 }, "heavily faded vintage photography"),
  mk("Antique", "古董老照片", { sat: -.35, temp: .25, grain: .30 }, "antique photograph, aged paper texture"),
  mk("Cinema", "标准电影感", { contrast: .15, sat: -.05 }, "cinematic color grading, film still"),
  mk("Teal & Orange", "青橙电影调色", { splitShadow: TEAL, splitHighlight: ORANGE, splitAmount: .35 }, "cinematic teal shadows, warm orange highlights"),
  mk("Noir", "黑色电影", { sat: -1, contrast: .30 }, "classic film noir, dramatic black and white"),
  mk("Drama", "戏剧高对比", { contrast: .25, exp: -.05 }, "dramatic cinematic lighting, deep shadows"),
  mk("Hollywood", "好莱坞电影感", { contrast: .12, sat: .05 }, "Hollywood cinematic color grading"),
  mk("Dark Cinema", "黑暗电影", { exp: -.15, contrast: .20 }, "dark cinematic photography, deep shadows"),
  mk("Epic", "大片质感", { contrast: .20, sat: .08 }, "epic movie still, dramatic cinematic color"),
  mk("Indie Film", "独立电影低饱和", { sat: -.18, fade: .08 }, "indie film aesthetic, muted analog colors"),
  mk("Cinematic Blue", "蓝色电影感", { temp: -.20, contrast: .15 }, "cinematic blue color grading"),
  mk("Cinematic Gold", "金色电影感", { temp: .18, contrast: .18 }, "cinematic golden color grading"),
  mk("Moody", "暗调氛围", { exp: -.10, sat: -.10 }, "moody photography, muted dark tones"),
  mk("Deep", "深色浓郁", { exp: -.15, contrast: .20 }, "deep rich cinematic tones"),
  mk("Shadow", "强调阴影", { shadows: -.20, contrast: .15 }, "dramatic shadows, dark atmospheric photography"),
  mk("Dark Brown", "深棕色调", { temp: .15, sat: -.15 }, "dark brown cinematic tones"),
  mk("Midnight", "深蓝黑夜", { exp: -.20, temp: -.20 }, "midnight blue night photography"),
  mk("Black Matte", "哑黑质感", { contrast: .15, fade: .08 }, "matte black cinematic photography"),
  mk("Smoky", "灰雾质感", { contrast: -.10, sat: -.15 }, "smoky muted atmospheric photography"),
  mk("Velvet", "深沉柔和", { contrast: .08, sat: -.08 }, "rich velvet tones, soft dark photography"),
  mk("After Dark", "夜晚城市", { exp: -.18, contrast: .18 }, "urban night photography, cinematic shadows"),
  mk("Dark Rose", "暗红紫色", { exp: -.10, channelSat: [.10, 0, 0], splitHighlight: ROSE_HI, splitAmount: .15 }, "dark rose tones, moody red and purple"),
  mk("Pastel", "粉彩低饱和", { sat: -.15, contrast: -.10 }, "pastel color palette, soft photography"),
  mk("Milky", "奶白色调", { exp: .12, contrast: -.15, fade: .08 }, "milky white tones, bright soft photography"),
  mk("Creamy", "奶油柔和", { temp: .12, contrast: -.12 }, "creamy warm photography"),
  mk("Baby Pink", "淡粉色调", { tint: .15, sat: -.05 }, "soft baby pink aesthetic"),
  mk("Peach Milk", "桃粉奶油", { temp: .12, tint: .12 }, "peach milk pastel tones"),
  mk("Lavender", "淡紫色调", { tint: .20, sat: -.08 }, "soft lavender pastel photography"),
  mk("Soft Beige", "米色极简", { temp: .15, sat: -.18 }, "minimalist beige aesthetic"),
  mk("Cloud", "白色柔光", { exp: .18, contrast: -.20 }, "bright cloud-like soft photography"),
  mk("Dreamy", "梦幻柔焦", { exp: .10, contrast: -.15, glow: .25 }, "dreamy soft-focus photography"),
  mk("K-Soft", "清透韩系", { exp: .10, sat: -.05, contrast: -.10 }, "soft Korean lifestyle photography"),
  mk("Vivid", "鲜艳饱和", { sat: .25 }, "vivid colorful photography"),
  mk("Pop", "高饱和高对比", { sat: .30, contrast: .15 }, "vibrant pop photography"),
  mk("Candy", "糖果色调", { sat: .25, tint: .05 }, "colorful candy pastel tones"),
  mk("Tropical", "热带色彩", { sat: .30, channelSat: [0, .15, 0] }, "vibrant tropical colors"),
  mk("Electric", "电子色彩", { sat: .35, contrast: .20 }, "vivid electric color grading"),
  mk("Neon", "霓虹灯效", { sat: .40, contrast: .20 }, "vibrant neon lights, saturated colors"),
  mk("Cyberpunk", "紫蓝霓虹", { channelSat: [0, 0, .25], splitShadow: BLUE_SHADOW, splitHighlight: PURPLE_HI, splitAmount: .25 }, "cyberpunk neon, blue and magenta lights"),
  mk("Purple Night", "紫色夜景", { exp: -.08, splitHighlight: PURPLE_HI, splitAmount: .30 }, "purple neon night photography"),
  mk("RGB", "强烈 RGB", { sat: .35, contrast: .20 }, "intense RGB lighting, digital aesthetic"),
  mk("Electric Blue", "强烈电蓝", { channelSat: [0, 0, .35] }, "intense electric blue photography"),
  mk("VHS", "VHS 录像带", { grain: .30, fade: .15, rgbShift: .15, vhs: .5 }, "authentic VHS tape aesthetic, analog noise"),
  mk("Camcorder", "家用摄像机", { sat: -.05, grain: .25, glow: .2 }, "1990s handheld camcorder aesthetic"),
  mk("Flash", "直接闪光灯", { contrast: .20, highlights: .15 }, "direct on-camera flash photography"),
  mk("Disposable Flash", "一次性闪光相机", { contrast: .15, grain: .30, vignette: .10 }, "disposable camera flash, harsh direct light"),
  mk("Dream", "梦境柔光", { contrast: -.20, glow: .35 }, "dreamy ethereal soft-focus photography"),
  mk("Glow", "高光发光", { highlights: .15, glow: .30 }, "glowing highlights, soft bloom"),
  mk("Prism", "棱镜彩虹", { rgbShift: .4, glow: .1 }, "prism light refraction, rainbow lens effects"),
  mk("Glitch", "数字故障", { rgbShift: .3, glitch: .6 }, "digital glitch art, RGB separation"),
  mk("Comic", "漫画风格", { edge: .8, posterize: 6, sat: .20 }, "comic book illustration, bold outlines"),
  mk("Anime", "二次元风格", { posterize: 8, edge: .4, sat: .15, glow: .1 }, "anime-inspired illustration, clean line art"),
];

window.FILTERS = FILTERS;
window.DEFAULT_PARAMS = DEFAULT_PARAMS;
