// filters.js — 100 filter presets.
// Every filter is a set of overrides merged onto DEFAULT_PARAMS.
// Numeric params roughly follow the original spec table, scaled to 0–1 shader units.

const DEFAULT_PARAMS = {
  exp: 0, contrast: 0, sat: 0, temp: 0, tint: 0,
  highlights: 0, shadows: 0, fade: 0, grain: 0, vignette: 0, clarity: 0,
  splitShadow: [0.5, 0.5, 0.5], splitHighlight: [0.5, 0.5, 0.5], splitAmount: 0,
  channelSat: [0, 0, 0],
  posterize: 0, edge: 0, rgbShift: 0, glitch: 0, dust: 0, glow: 0, vhs: 0,
};

function mk(en, cn, overrides, prompt) {
  return { en, cn, prompt, params: Object.assign({}, DEFAULT_PARAMS, overrides) };
}

const TEAL = [0.40, 0.50, 0.58];
const ORANGE = [0.62, 0.52, 0.40];
const ROSE_HI = [0.58, 0.42, 0.55];
const PURPLE_HI = [0.56, 0.38, 0.62];
const BLUE_SHADOW = [0.42, 0.42, 0.62];

const FILTERS = [
  mk("Pure", "Clean True Color", { exp: .03, contrast: .03, sat: .02 }, "natural realistic colors, subtle enhancement"),
  mk("Clean", "Clear Modern", { exp: .06, contrast: .04, sat: .03 }, "clean modern photography, clear natural colors"),
  mk("Fresh", "Bright Fresh", { exp: .08, temp: -.05, sat: .05 }, "fresh bright photography, slightly cool tones"),
  mk("Clear", "Layered Clarity", { contrast: .08, highlights: -.08, shadows: .08 }, "crystal clear details, balanced dynamic range"),
  mk("Bright", "Overall Bright", { exp: .12, shadows: .10 }, "bright airy photography, lifted shadows"),
  mk("Soft", "Soft Low Contrast", { contrast: -.08, highlights: -.05, fade: .05 }, "soft photography, gentle contrast, smooth tones"),
  mk("Airy", "Light High Key", { exp: .15, contrast: -.08, sat: -.02 }, "airy high-key photography, soft whites"),
  mk("Pure Skin", "Natural Skin", { exp: .05, sat: -.02, channelSat: [-.08, 0, 0] }, "natural skin tones, clean portrait photography"),
  mk("Crystal", "Crisp Detail", { contrast: .10, clarity: .12, sat: .03 }, "crisp detailed photography, sharp textures"),
  mk("True Color", "Accurate Color", { contrast: .02, sat: -.02 }, "accurate true-to-life colors"),
  mk("Warm", "Warm Tone", { temp: .12, sat: .03 }, "warm natural photography, cozy tones"),
  mk("Golden", "Golden Sun", { temp: .22, highlights: .05 }, "golden sunlight, warm highlights"),
  mk("Honey", "Honey Warmth", { temp: .28, sat: .05, fade: .03 }, "honey golden tones, warm soft photography"),
  mk("Peach", "Peach Pink", { temp: .15, tint: .08 }, "peach tones, soft warm portrait"),
  mk("Cream", "Cream Tone", { temp: .18, contrast: -.08, fade: .08 }, "creamy warm tones, soft highlights"),
  mk("Latte", "Latte Cream", { temp: .25, sat: -.08, fade: .10 }, "latte beige tones, muted warm colors"),
  mk("Sunset", "Sunset Orange Red", { temp: .30, channelSat: [.15, .07, 0] }, "dramatic sunset orange tones"),
  mk("Amber", "Deep Amber", { temp: .25, contrast: .08 }, "rich amber color grading"),
  mk("Apricot", "Apricot Peach", { temp: .20, tint: .12 }, "soft apricot and peach tones"),
  mk("Summer Glow", "Summer Sun", { exp: .08, temp: .18, sat: .08 }, "bright summer sunlight, warm glow"),
  mk("Cool", "Slightly Cool", { temp: -.15 }, "cool clean color grading"),
  mk("Ice", "Ice Blue", { temp: -.30, sat: -.05 }, "icy blue tones, cold atmosphere"),
  mk("Arctic", "Cold Blue Gray", { temp: -.35, contrast: .05 }, "arctic cold tones, blue-gray palette"),
  mk("Ocean", "Ocean Blue", { temp: -.20, channelSat: [0, 0, .15] }, "deep ocean blue tones"),
  mk("Blue Hour", "Blue Twilight", { temp: -.30, exp: -.05, channelSat: [0, 0, .12] }, "blue hour photography, cool twilight"),
  mk("Frost", "Frost Texture", { temp: -.35, sat: -.10 }, "frosty muted blue atmosphere"),
  mk("Cyan", "Cyan Blue", { temp: -.20, tint: -.08 }, "cyan color grading, cool tones"),
  mk("Deep Blue", "Deep Cinema Blue", { temp: -.25, contrast: .15 }, "deep cinematic blue tones"),
  mk("Rain", "Rainy Day", { exp: -.08, sat: -.12, temp: -.18 }, "rainy day photography, muted cool tones"),
  mk("Winter", "Winter Cool", { temp: -.25, highlights: -.08 }, "winter photography, cool clean highlights"),
  mk("35mm", "Classic Film", { contrast: -.05, fade: .08, grain: .18 }, "authentic 35mm analog film, subtle grain"),
  mk("Portra", "Soft Skin Film", { sat: -.08, contrast: -.05, grain: .12 }, "portrait film, natural skin tones, soft grain"),
  mk("Kodak", "Warm Yellow Film", { temp: .10, sat: .05, grain: .15 }, "Kodak-inspired warm 35mm film aesthetic"),
  mk("Fuji", "Fresh Green Film", { temp: -.03, channelSat: [0, .08, 0], grain: .12 }, "Fuji-inspired film, subtle green tones"),
  mk("Classic Film", "Traditional Film", { sat: -.08, fade: .12, grain: .20 }, "classic analog film, faded colors, grain"),
  mk("Soft Film", "Soft Film", { contrast: -.12, fade: .12, grain: .15 }, "soft film photography, gentle contrast"),
  mk("Negative", "Negative Film", { sat: -.10, contrast: -.08, grain: .22 }, "negative film aesthetic, analog texture"),
  mk("Disposable", "Disposable Camera", { contrast: .05, grain: .30, vignette: .12 }, "disposable camera aesthetic, flash, grain"),
  mk("Analog", "Analog Camera", { fade: .10, grain: .25, sat: -.05 }, "authentic analog camera photography"),
  mk("Film Dust", "Film Dust Texture", { grain: .25, fade: .15, dust: .5 }, "vintage film with dust and scratches"),
  mk("Vintage", "Yellowed Fade", { temp: .18, fade: .20 }, "nostalgic vintage photography, faded colors"),
  mk("Retro", "Retro Era", { sat: -.05, temp: .12, grain: .20 }, "retro analog photography, nostalgic colors"),
  mk("Sepia", "Old Sepia Photo", { sat: -.45, temp: .35 }, "classic sepia photograph"),
  mk("Old Camera", "Old Camera Texture", { contrast: -.05, grain: .30, fade: .20 }, "old camera photography, faded grain"),
  mk("90s", "90s Film", { sat: .03, grain: .25, fade: .10 }, "authentic 1990s film photography"),
  mk("80s", "80s Warm", { temp: .20, sat: .08, grain: .25 }, "1980s vintage photography, warm colors"),
  mk("70s", "70s Yellow Brown", { temp: .30, sat: -.05, fade: .20 }, "1970s film photography, warm faded tones"),
  mk("Nostalgia", "Soft Nostalgia", { contrast: -.10, fade: .18, grain: .15 }, "nostalgic dreamy analog photography"),
  mk("Faded", "Heavy Fade", { contrast: -.15, fade: .30 }, "heavily faded vintage photography"),
  mk("Antique", "Antique Photo", { sat: -.35, temp: .25, grain: .30 }, "antique photograph, aged paper texture"),
  mk("Cinema", "Standard Cinema", { contrast: .15, sat: -.05 }, "cinematic color grading, film still"),
  mk("Teal & Orange", "Teal Orange Cinema", { splitShadow: TEAL, splitHighlight: ORANGE, splitAmount: .35 }, "cinematic teal shadows, warm orange highlights"),
  mk("Noir", "Film Noir", { sat: -1, contrast: .30 }, "classic film noir, dramatic black and white"),
  mk("Drama", "High Contrast Drama", { contrast: .25, exp: -.05 }, "dramatic cinematic lighting, deep shadows"),
  mk("Hollywood", "Hollywood Cinema", { contrast: .12, sat: .05 }, "Hollywood cinematic color grading"),
  mk("Dark Cinema", "Dark Cinema", { exp: -.15, contrast: .20 }, "dark cinematic photography, deep shadows"),
  mk("Epic", "Blockbuster Texture", { contrast: .20, sat: .08 }, "epic movie still, dramatic cinematic color"),
  mk("Indie Film", "Low Saturation Indie", { sat: -.18, fade: .08 }, "indie film aesthetic, muted analog colors"),
  mk("Cinematic Blue", "Cinema Blue", { temp: -.20, contrast: .15 }, "cinematic blue color grading"),
  mk("Cinematic Gold", "Cinema Gold", { temp: .18, contrast: .18 }, "cinematic golden color grading"),
  mk("Moody", "Dark Mood", { exp: -.10, sat: -.10 }, "moody photography, muted dark tones"),
  mk("Deep", "Deep Rich Tone", { exp: -.15, contrast: .20 }, "deep rich cinematic tones"),
  mk("Shadow", "Shadow Emphasis", { shadows: -.20, contrast: .15 }, "dramatic shadows, dark atmospheric photography"),
  mk("Dark Brown", "Dark Brown Tone", { temp: .15, sat: -.15 }, "dark brown cinematic tones"),
  mk("Midnight", "Deep Blue Night", { exp: -.20, temp: -.20 }, "midnight blue night photography"),
  mk("Black Matte", "Matte Black", { contrast: .15, fade: .08 }, "matte black cinematic photography"),
  mk("Smoky", "Smoky Gray", { contrast: -.10, sat: -.15 }, "smoky muted atmospheric photography"),
  mk("Velvet", "Deep Soft", { contrast: .08, sat: -.08 }, "rich velvet tones, soft dark photography"),
  mk("After Dark", "Night City", { exp: -.18, contrast: .18 }, "urban night photography, cinematic shadows"),
  mk("Dark Rose", "Dark Red Purple", { exp: -.10, channelSat: [.10, 0, 0], splitHighlight: ROSE_HI, splitAmount: .15 }, "dark rose tones, moody red and purple"),
  mk("Pastel", "Low Saturation Pastel", { sat: -.15, contrast: -.10 }, "pastel color palette, soft photography"),
  mk("Milky", "Milky White", { exp: .12, contrast: -.15, fade: .08 }, "milky white tones, bright soft photography"),
  mk("Creamy", "Creamy Soft", { temp: .12, contrast: -.12 }, "creamy warm photography"),
  mk("Baby Pink", "Light Pink", { tint: .15, sat: -.05 }, "soft baby pink aesthetic"),
  mk("Peach Milk", "Peach Cream", { temp: .12, tint: .12 }, "peach milk pastel tones"),
  mk("Lavender", "Light Purple", { tint: .20, sat: -.08 }, "soft lavender pastel photography"),
  mk("Soft Beige", "Minimal Beige", { temp: .15, sat: -.18 }, "minimalist beige aesthetic"),
  mk("Cloud", "White Soft Light", { exp: .18, contrast: -.20 }, "bright cloud-like soft photography"),
  mk("Dreamy", "Dreamy Soft Focus", { exp: .10, contrast: -.15, glow: .25 }, "dreamy soft-focus photography"),
  mk("K-Soft", "Clear Korean Style", { exp: .10, sat: -.05, contrast: -.10 }, "soft Korean lifestyle photography"),
  mk("Vivid", "Vivid Saturation", { sat: .25 }, "vivid colorful photography"),
  mk("Pop", "High Sat High Contrast", { sat: .30, contrast: .15 }, "vibrant pop photography"),
  mk("Candy", "Candy Color", { sat: .25, tint: .05 }, "colorful candy pastel tones"),
  mk("Tropical", "Tropical Color", { sat: .30, channelSat: [0, .15, 0] }, "vibrant tropical colors"),
  mk("Electric", "Electric Color", { sat: .35, contrast: .20 }, "vivid electric color grading"),
  mk("Neon", "Neon Light", { sat: .40, contrast: .20 }, "vibrant neon lights, saturated colors"),
  mk("Cyberpunk", "Purple Blue Neon", { channelSat: [0, 0, .25], splitShadow: BLUE_SHADOW, splitHighlight: PURPLE_HI, splitAmount: .25 }, "cyberpunk neon, blue and magenta lights"),
  mk("Purple Night", "Purple Nightscape", { exp: -.08, splitHighlight: PURPLE_HI, splitAmount: .30 }, "purple neon night photography"),
  mk("RGB", "Strong RGB", { sat: .35, contrast: .20 }, "intense RGB lighting, digital aesthetic"),
  mk("Electric Blue", "Strong Electric Blue", { channelSat: [0, 0, .35] }, "intense electric blue photography"),
  mk("VHS", "VHS Tape", { grain: .30, fade: .15, rgbShift: .15, vhs: .5 }, "authentic VHS tape aesthetic, analog noise"),
  mk("Camcorder", "Home Camcorder", { sat: -.05, grain: .25, glow: .2 }, "1990s handheld camcorder aesthetic"),
  mk("Flash", "Direct Flash", { contrast: .20, highlights: .15 }, "direct on-camera flash photography"),
  mk("Disposable Flash", "Disposable Flash Camera", { contrast: .15, grain: .30, vignette: .10 }, "disposable camera flash, harsh direct light"),
  mk("Dream", "Dream Soft Light", { contrast: -.20, glow: .35 }, "dreamy ethereal soft-focus photography"),
  mk("Glow", "Glowing Highlights", { highlights: .15, glow: .30 }, "glowing highlights, soft bloom"),
  mk("Prism", "Prism Rainbow", { rgbShift: .4, glow: .1 }, "prism light refraction, rainbow lens effects"),
  mk("Glitch", "Digital Glitch", { rgbShift: .3, glitch: .6 }, "digital glitch art, RGB separation"),
  mk("Comic", "Comic Style", { edge: .8, posterize: 6, sat: .20 }, "comic book illustration, bold outlines"),
  mk("Anime", "Anime Style", { posterize: 8, edge: .4, sat: .15, glow: .1 }, "anime-inspired illustration, clean line art"),
];

window.FILTERS = FILTERS;
window.DEFAULT_PARAMS = DEFAULT_PARAMS;
